/* 数据模块：cards（由 data.js 拆分，结构原样保留；可用 G.def 注册器继续叠加扩展） */
var G = window.GAME.data || (window.GAME.data = {})
G.BATTLE_REWARD_CARDS = [
  { name: '蓄力重击', desc: '凝聚全力挥出重拳，造成 12 点伤害。', energyCost: 2, damage: 12 },
  { name: '猛烈撕咬', desc: '迅猛扑咬，造成 5 点伤害。', energyCost: 1, damage: 5 },
  { name: '铁壁防御', desc: '摆出铁壁架势，获得 8 点格挡。', energyCost: 1, block: 8 },
  { name: '硬化外壳', desc: '硬化表皮，获得 14 点格挡。', energyCost: 2, block: 14 },
  { name: '蓄能', desc: '深呼吸凝聚战斗能量 +2。', energyCost: 0, energyGain: 2 },
  { name: '战术呼吸', desc: '调整呼吸，能量 +1 并抽 1 张牌。', energyCost: 1, energyGain: 1, draw: 1 },
  { name: '灼烧之爪', desc: '燃火利爪，造成 4 点伤害并施加 2 层灼烧。', energyCost: 1, damage: 4, element: 'fire', elementAmount: 2 },
  { name: '毒牙', desc: '毒牙噬咬，造成 3 点伤害并施加 3 层剧毒。', energyCost: 1, damage: 3, element: 'poison', elementAmount: 3 },
  { name: '静电冲击', desc: '释放静电，造成 2 点伤害并施加 2 层雷击。', energyCost: 1, damage: 2, element: 'lightning', elementAmount: 2 },
  { name: '水蚀刃', desc: '水刃切割，造成 3 点伤害并施加 2 层水蚀。', energyCost: 1, damage: 3, element: 'water', elementAmount: 2 },
  { name: '冰刺', desc: '凝结冰刺，造成 2 点伤害并施加 2 层冰封。', energyCost: 1, damage: 2, element: 'ice', elementAmount: 2 },
  { name: '风刃斩', desc: '挥出风刃，造成 3 点伤害并施加 2 层风袭。', energyCost: 1, damage: 3, element: 'wind', elementAmount: 2 },
  { name: '吸血撕咬', desc: '咬住猎物汲取生机，造成 7 点伤害并恢复 3 点生命。', energyCost: 2, damage: 7, heal: 3 },
  { name: '战意', desc: '点燃战意，下回合你的攻击伤害 ×2（一次）。', energyCost: 0, doubleNext: true },
  { name: '骨甲术', desc: '骨骼护甲护体，获得 6 点格挡，本回合免疫伤害。', energyCost: 2, block: 6, invulnerable: true },
  { name: '猎手连击', desc: '快速连击，造成 4 点伤害并抽 1 张牌。', energyCost: 1, damage: 4, draw: 1 },
]

// ---- 奖励卡牌池：手写 212 张，按星级（1-5）分池，生物难度越高掉落星级越高 ----
// 星级强度基准：1星普通 → 5星传说；掉落时按敌人战力选取 1-2 个相邻星级混合
G.REWARD_CARDS = {
  1: [
    { name: '突刺拳', desc: '快如疾风的刺拳，造成 4 点伤害。', energyCost: 1, damage: 4, star: 1 },
    { name: '猛力劈砍', desc: '全力劈下，造成 8 点伤害。', energyCost: 2, damage: 8, star: 1 },
    { name: '基本防御', desc: '摆出防御架势，获得 5 点格挡。', energyCost: 1, block: 5, star: 1 },
    { name: '龟缩', desc: '抱头蹲防，获得 10 点格挡。', energyCost: 2, block: 10, star: 1 },
    { name: '火种', desc: '掷出火星，造成 2 点伤害并施加 2 层灼烧。', energyCost: 1, damage: 2, element: 'fire', elementAmount: 2, star: 1 },
    { name: '冰晶', desc: '掷出冰晶，造成 2 点伤害并施加 2 层冰封。', energyCost: 1, damage: 2, element: 'ice', elementAmount: 2, star: 1 },
    { name: '毒刺', desc: '毒刺划伤，造成 2 点伤害并施加 3 层剧毒。', energyCost: 1, damage: 2, element: 'poison', elementAmount: 3, star: 1 },
    { name: '电击', desc: '指尖放电，造成 2 点伤害并施加 2 层雷击。', energyCost: 1, damage: 2, element: 'lightning', elementAmount: 2, star: 1 },
    { name: '水刃', desc: '挥出水刃，造成 3 点伤害并施加 2 层水蚀。', energyCost: 1, damage: 3, element: 'water', elementAmount: 2, star: 1 },
    { name: '风切', desc: '甩出风刃，造成 3 点伤害并施加 2 层风袭。', energyCost: 1, damage: 3, element: 'wind', elementAmount: 2, star: 1 },
    { name: '火球', desc: '凝聚火球掷出，造成 4 点伤害并施加 3 层灼烧。', energyCost: 2, damage: 4, element: 'fire', elementAmount: 3, star: 1 },
    { name: '冰锥', desc: '凝出冰锥刺出，造成 4 点伤害并施加 3 层冰封。', energyCost: 2, damage: 4, element: 'ice', elementAmount: 3, star: 1 },
    { name: '毒雾', desc: '喷出毒雾，造成 3 点伤害并施加 4 层剧毒。', energyCost: 2, damage: 3, element: 'poison', elementAmount: 4, star: 1 },
    { name: '雷击', desc: '召唤落雷，造成 4 点伤害并施加 3 层雷击。', energyCost: 2, damage: 4, element: 'lightning', elementAmount: 3, star: 1 },
    { name: '水球', desc: '砸出水球，造成 4 点伤害并施加 3 层水蚀。', energyCost: 2, damage: 4, element: 'water', elementAmount: 3, star: 1 },
    { name: '旋风', desc: '卷起旋风，造成 4 点伤害并施加 3 层风袭。', energyCost: 2, damage: 4, element: 'wind', elementAmount: 3, star: 1 },
    { name: '小口进食', desc: '就地进食恢复体力，恢复 2 点生命。', energyCost: 1, heal: 2, star: 1 },
    { name: '疗伤草药', desc: '敷上草药，恢复 4 点生命。', energyCost: 2, heal: 4, star: 1 },
    { name: '深呼吸', desc: '调整呼吸，获得 2 点能量。', energyCost: 0, energyGain: 2, star: 1 },
    { name: '精神振奋', desc: '提振精神，获得 2 点能量并抽 1 张牌。', energyCost: 1, energyGain: 2, draw: 1, star: 1 },
    { name: '翻找', desc: '翻找行囊，抽 2 张牌。', energyCost: 1, draw: 2, star: 1 },
    { name: '蓄力一击', desc: '收势蓄力，下回合攻击伤害 ×2（一次）。', energyCost: 0, doubleNext: true, star: 1 },
    { name: '组合拳', desc: '连环出拳，造成 4 点伤害并抽 1 张牌。', energyCost: 2, damage: 4, draw: 1, star: 1 },
    { name: '攻防一体', desc: '攻守兼备，造成 3 点伤害并获得 3 点格挡。', energyCost: 2, damage: 3, block: 3, star: 1 },
    { name: '防御反击', desc: '格挡后反击，造成 4 点伤害并获得 4 点格挡。', energyCost: 2, damage: 4, block: 4, star: 1 },
    { name: '绊腿', desc: '绊倒对手，造成 3 点伤害并抽 1 张牌。', energyCost: 1, damage: 3, draw: 1, star: 1 },
    { name: '怒火', desc: '燃起怒火，获得 1 点力量（本场战斗攻击伤害 +1）。', energyCost: 1, strength: 1, star: 1 },
    { name: '身轻', desc: '放松身形，获得 1 点敏捷（本场战斗格挡 +1）。', energyCost: 1, dexterity: 1, star: 1 },
    { name: '威慑', desc: '大喝威慑敌人，使其攻击伤害 -25%。', energyCost: 0, applyWeak: 1, star: 1 },
    { name: '弱点打击', desc: '直击弱点，造成 3 点伤害并施加 2 层易伤（受击 +50%）。', energyCost: 1, damage: 3, applyVuln: 2, star: 1 },
    { name: '舍身一击', desc: '舍弃防御的一击，造成 10 点伤害并失去 3 点生命。', energyCost: 2, damage: 10, loseLife: 3, star: 1 },
    { name: '战吼', desc: '怒吼提振士气，抽 2 张牌（消耗）。', energyCost: 0, draw: 2, exhaust: true, star: 1 },
    { name: '连击拳', desc: '连续快拳，造成 2 点伤害 ×2 次。', energyCost: 1, damage: 2, hits: 2, star: 1 },
    { name: '破盾斩', desc: '专破硬壳的斩击，造成 7 点伤害并无视敌人护盾。', energyCost: 2, damage: 7, pierce: true, star: 1 },
    { name: '腐蚀之触', desc: '沾染腐蚀之力，造成 1 点伤害并施加 2 层腐蚀（腐蚀会不断蔓延）。', energyCost: 1, damage: 1, element: 'corrode', elementAmount: 2, star: 1 },
    { name: '以牙还牙', desc: '摆出以牙还牙架势，本回合受到攻击时反伤 4 点。', energyCost: 1, retaliate: 4, star: 1 },
    { name: '临时狂热', desc: '肾上腺素飙升，获得 2 点临时力量（仅本回合有效）。', energyCost: 0, tempStrength: 2, star: 1 },
    { name: '回响预备', desc: '凝聚回响之力，本回合下一张牌的效果将执行两次。', energyCost: 1, echo: 1, star: 1 },
    { name: '每日淬炼', desc: '能力：每回合开始时获得 1 点力量。', energyCost: 1, perTurn: { str: 1 }, star: 1 },
    { name: '荆棘藤蔓', desc: '长出荆棘护体，每次受击反伤 3 点（整场战斗持续）。', energyCost: 1, thorns: 3, star: 1 },
    { name: '缴械打击', desc: '精准卸下武器，造成 2 点伤害并使敌人攻击永久 -1。', energyCost: 1, damage: 2, enemyAtkDown: 1, star: 1 },
    { name: '磨刀石', desc: '磨砺利刃，造成 3 点伤害，本场战斗每次使用后伤害 +2。', energyCost: 1, damage: 3, rampage: 2, star: 1 },
  ],
  2: [
    { name: '剑术·斜斩', desc: '刁钻的斜向斩击，造成 6 点伤害。', energyCost: 1, damage: 6, star: 2 },
    { name: '铁壁重击', desc: '铁壁般的重击，造成 13 点伤害。', energyCost: 3, damage: 13, star: 2 },
    { name: '快刀', desc: '连挥快刀，造成 5 点伤害并抽 1 张牌。', energyCost: 1, damage: 5, draw: 1, star: 2 },
    { name: '招架', desc: '精准招架，获得 8 点格挡。', energyCost: 1, block: 8, star: 2 },
    { name: '硬化', desc: '全面硬化体表，获得 14 点格挡。', energyCost: 2, block: 14, star: 2 },
    { name: '烈焰斩', desc: '燃火挥斩，造成 6 点伤害并施加 3 层灼烧。', energyCost: 2, damage: 6, element: 'fire', elementAmount: 3, star: 2 },
    { name: '寒冰刺', desc: '凝冰突刺，造成 6 点伤害并施加 3 层冰封。', energyCost: 2, damage: 6, element: 'ice', elementAmount: 3, star: 2 },
    { name: '剧毒爪', desc: '毒爪撕扯，造成 5 点伤害并施加 4 层剧毒。', energyCost: 2, damage: 5, element: 'poison', elementAmount: 4, star: 2 },
    { name: '雷霆一击', desc: '带电猛击，造成 6 点伤害并施加 3 层雷击。', energyCost: 2, damage: 6, element: 'lightning', elementAmount: 3, star: 2 },
    { name: '水龙卷', desc: '卷起水龙卷，造成 6 点伤害并施加 3 层水蚀。', energyCost: 2, damage: 6, element: 'water', elementAmount: 3, star: 2 },
    { name: '风暴之刃', desc: '风刃横扫，造成 6 点伤害并施加 3 层风袭。', energyCost: 2, damage: 6, element: 'wind', elementAmount: 3, star: 2 },
    { name: '火流星', desc: '召唤火流星，造成 9 点伤害并施加 4 层灼烧。', energyCost: 3, damage: 9, element: 'fire', elementAmount: 4, star: 2 },
    { name: '冰封大地', desc: '冰封地面，造成 8 点伤害并施加 4 层冰封。', energyCost: 3, damage: 8, element: 'ice', elementAmount: 4, star: 2 },
    { name: '毒云', desc: '降下毒云，造成 7 点伤害并施加 5 层剧毒。', energyCost: 3, damage: 7, element: 'poison', elementAmount: 5, star: 2 },
    { name: '雷暴', desc: '引下雷暴，造成 9 点伤害并施加 4 层雷击。', energyCost: 3, damage: 9, element: 'lightning', elementAmount: 4, star: 2 },
    { name: '潮汐之力', desc: '借潮汐重击，造成 9 点伤害并施加 4 层水蚀。', energyCost: 3, damage: 9, element: 'water', elementAmount: 4, star: 2 },
    { name: '飓风', desc: '召唤飓风，造成 9 点伤害并施加 4 层风袭。', energyCost: 3, damage: 9, element: 'wind', elementAmount: 4, star: 2 },
    { name: '血之渴望', desc: '渴望鲜血的撕咬，造成 7 点伤害并恢复 3 点生命。', energyCost: 2, damage: 7, heal: 3, star: 2 },
    { name: '汲取生命', desc: '汲取敌人生机，造成 6 点伤害并恢复 4 点生命。', energyCost: 2, damage: 6, heal: 4, star: 2 },
    { name: '战斗包扎', desc: '包扎伤口，恢复 4 点生命。', energyCost: 1, heal: 4, star: 2 },
    { name: '草药精华', desc: '服下草药精华，恢复 6 点生命。', energyCost: 2, heal: 6, star: 2 },
    { name: '凝神静气', desc: '屏息凝神，获得 3 点能量。', energyCost: 0, energyGain: 3, star: 2 },
    { name: '战术呼吸', desc: '战术性换气，获得 2 点能量并抽 1 张牌。', energyCost: 1, energyGain: 2, draw: 1, star: 2 },
    { name: '深思熟虑', desc: '冷静思考，抽 2 张牌并获得 1 点能量。', energyCost: 1, draw: 2, energyGain: 1, star: 2 },
    { name: '战术抽牌', desc: '寻找战术机会，抽 3 张牌。', energyCost: 1, draw: 3, star: 2 },
    { name: '双重斩', desc: '连续斩击，造成 5 点伤害并抽 1 张牌。', energyCost: 2, damage: 5, draw: 1, star: 2 },
    { name: '追风连斩', desc: '追风连斩，造成 6 点伤害并抽 1 张牌。', energyCost: 2, damage: 6, draw: 1, star: 2 },
    { name: '强化反击', desc: '防守反击，造成 5 点伤害并获得 5 点格挡。', energyCost: 2, damage: 5, block: 5, star: 2 },
    { name: '攻守转换', desc: '转守为攻，造成 6 点伤害并获得 4 点格挡。', energyCost: 2, damage: 6, block: 4, star: 2 },
    { name: '燃烧瓶', desc: '掷出燃烧瓶，造成 3 点伤害并施加 4 层灼烧。', energyCost: 1, damage: 3, element: 'fire', elementAmount: 4, star: 2 },
    { name: '毒瓶', desc: '掷出毒瓶，造成 3 点伤害并施加 4 层剧毒。', energyCost: 1, damage: 3, element: 'poison', elementAmount: 4, star: 2 },
    { name: '怒火中烧', desc: '怒火沸腾，获得 1 点力量。', energyCost: 0, strength: 1, star: 2 },
    { name: '蓄势', desc: '沉腰蓄势，获得 2 点力量。', energyCost: 2, strength: 2, star: 2 },
    { name: '轻灵步伐', desc: '步伐轻灵，获得 2 点敏捷。', energyCost: 1, dexterity: 2, star: 2 },
    { name: '威慑强化', desc: '强力威慑，使敌人攻击伤害 -25%（叠加）。', energyCost: 0, applyWeak: 2, star: 2 },
    { name: '弱点重击', desc: '重击破绽，造成 6 点伤害并施加 3 层易伤。', energyCost: 2, damage: 6, applyVuln: 3, star: 2 },
    { name: '血祭', desc: '献祭血肉，造成 15 点伤害并失去 5 点生命。', energyCost: 2, damage: 15, loseLife: 5, star: 2 },
    { name: '战吼·重', desc: '响亮战吼，抽 3 张牌（消耗）。', energyCost: 1, draw: 3, exhaust: true, star: 2 },
    { name: '保留战术', desc: '抽 1 张牌，此牌回合结束保留在手牌。', energyCost: 1, draw: 1, retain: true, star: 2 },
    { name: '三重刺', desc: '连续突刺，造成 3 点伤害 ×3 次。', energyCost: 2, damage: 3, hits: 3, star: 2 },
    { name: '破甲斩', desc: '破甲利刃，造成 10 点伤害并无视敌人护盾。', energyCost: 2, damage: 10, pierce: true, star: 2 },
    { name: '腐蚀之刃', desc: '腐蚀淬刃，造成 4 点伤害并施加 3 层腐蚀（腐蚀会不断蔓延）。', energyCost: 1, damage: 4, element: 'corrode', elementAmount: 3, star: 2 },
    { name: '剧毒引爆', desc: '引爆敌人体内毒素，造成 2 点伤害并立即结算毒层 ×2（清除剧毒）。', energyCost: 1, damage: 2, poisonBurst: true, star: 2 },
    { name: '吸血撕咬', desc: '咬住猎物不放，造成 5 点伤害并恢复等量生命。', energyCost: 1, damage: 5, lifesteal: true, star: 2 },
    { name: '眩晕打击', desc: '重击头部，造成 4 点伤害并使敌人下回合无法行动。', energyCost: 2, damage: 4, stun: true, star: 2 },
    { name: '稳固', desc: '稳住下盘，获得 6 点格挡，本回合格挡不会在受击后清零。', energyCost: 1, block: 6, fortify: true, star: 2 },
    { name: '回响斩', desc: '造成 5 点伤害，本回合下一张牌的效果将执行两次。', energyCost: 2, damage: 5, echo: 1, star: 2 },
    { name: '恶魔契约', desc: '能力：每回合开始时获得 2 点力量。', energyCost: 2, perTurn: { str: 2 }, star: 2 },
    { name: '荆棘甲胄', desc: '获得 4 点格挡和 4 点荆棘（整场战斗持续）。', energyCost: 1, block: 4, thorns: 4, star: 2 },
    { name: '断筋', desc: '斩断筋腱，造成 4 点伤害并使敌人攻击永久 -1。', energyCost: 1, damage: 4, enemyAtkDown: 1, star: 2 },
    { name: '山峦之躯', desc: '能力：每回合开始时获得 4 点格挡。', energyCost: 1, perTurn: { block: 4 }, star: 2 },
    { name: '清场旋风', desc: '弃置所有手牌，每弃一张对敌造成 3 点伤害。', energyCost: 1, discardGainDamage: 3, star: 2 },
  ],
  3: [
    { name: '剑术·强袭', desc: '凌厉强袭，造成 8 点伤害。', energyCost: 1, damage: 8, star: 3 },
    { name: '崩天一击', desc: '崩天撼地的一击，造成 17 点伤害。', energyCost: 3, damage: 17, star: 3 },
    { name: '影袭', desc: '阴影中突袭，造成 7 点伤害并抽 1 张牌。', energyCost: 1, damage: 7, draw: 1, star: 3 },
    { name: '毒匕', desc: '淬毒匕首，造成 4 点伤害并施加 6 层剧毒。', energyCost: 1, damage: 4, element: 'poison', elementAmount: 6, star: 3 },
    { name: '火绳镖', desc: '燃火飞镖，造成 4 点伤害并施加 6 层灼烧。', energyCost: 1, damage: 4, element: 'fire', elementAmount: 6, star: 3 },
    { name: '雷标枪', desc: '带电标枪，造成 4 点伤害并施加 6 层雷击。', energyCost: 1, damage: 4, element: 'lightning', elementAmount: 6, star: 3 },
    { name: '冰锥术', desc: '寒冰标枪，造成 4 点伤害并施加 6 层冰封。', energyCost: 1, damage: 4, element: 'ice', elementAmount: 6, star: 3 },
    { name: '完美格挡', desc: '完美架招，获得 11 点格挡。', energyCost: 1, block: 11, star: 3 },
    { name: '堡垒', desc: '化身堡垒，获得 18 点格挡。', energyCost: 2, block: 18, star: 3 },
    { name: '烈焰风暴', desc: '火海席卷，造成 9 点伤害并施加 4 层灼烧。', energyCost: 2, damage: 9, element: 'fire', elementAmount: 4, star: 3 },
    { name: '寒冰风暴', desc: '冰霜席卷，造成 9 点伤害并施加 4 层冰封。', energyCost: 2, damage: 9, element: 'ice', elementAmount: 4, star: 3 },
    { name: '剧毒之刃', desc: '淬毒利刃，造成 8 点伤害并施加 5 层剧毒。', energyCost: 2, damage: 8, element: 'poison', elementAmount: 5, star: 3 },
    { name: '海啸斩', desc: '借海啸之力斩击，造成 9 点伤害并施加 4 层水蚀。', energyCost: 2, damage: 9, element: 'water', elementAmount: 4, star: 3 },
    { name: '龙卷风', desc: '卷起龙卷风，造成 9 点伤害并施加 4 层风袭。', energyCost: 2, damage: 9, element: 'wind', elementAmount: 4, star: 3 },
    { name: '火凤凰', desc: '火凤降临，造成 13 点伤害并施加 5 层灼烧。', energyCost: 3, damage: 13, element: 'fire', elementAmount: 5, star: 3 },
    { name: '绝对零度', desc: '极寒冻结，造成 12 点伤害并施加 5 层冰封。', energyCost: 3, damage: 12, element: 'ice', elementAmount: 5, star: 3 },
    { name: '万毒归宗', desc: '剧毒汇聚，造成 11 点伤害并施加 6 层剧毒。', energyCost: 3, damage: 11, element: 'poison', elementAmount: 6, star: 3 },
    { name: '天雷', desc: '天雷降世，造成 13 点伤害并施加 5 层雷击。', energyCost: 3, damage: 13, element: 'lightning', elementAmount: 5, star: 3 },
    { name: '洪水', desc: '洪水倾泻，造成 13 点伤害并施加 5 层水蚀。', energyCost: 3, damage: 13, element: 'water', elementAmount: 5, star: 3 },
    { name: '风暴之眼', desc: '风暴核心，造成 13 点伤害并施加 5 层风袭。', energyCost: 3, damage: 13, element: 'wind', elementAmount: 5, star: 3 },
    { name: '吸血鬼之爪', desc: '血爪撕咬，造成 10 点伤害并恢复 4 点生命。', energyCost: 2, damage: 10, heal: 4, star: 3 },
    { name: '灵魂汲取', desc: '汲取灵魂，造成 9 点伤害并恢复 5 点生命。', energyCost: 2, damage: 9, heal: 5, star: 3 },
    { name: '战地急救', desc: '紧急包扎，恢复 6 点生命。', energyCost: 1, heal: 6, star: 3 },
    { name: '灵药', desc: '饮下灵药，恢复 9 点生命。', energyCost: 2, heal: 9, star: 3 },
    { name: '冥想', desc: '深度冥想，获得 4 点能量。', energyCost: 0, energyGain: 4, star: 3 },
    { name: '战术大师', desc: '战术大师的呼吸，获得 3 点能量并抽 1 张牌。', energyCost: 1, energyGain: 3, draw: 1, star: 3 },
    { name: '布局', desc: '提前布局，抽 3 张牌并获得 1 点能量。', energyCost: 1, draw: 3, energyGain: 1, star: 3 },
    { name: '深谋', desc: '深谋远虑，抽 4 张牌。', energyCost: 2, draw: 4, star: 3 },
    { name: '双重连斩', desc: '双刃连斩，造成 8 点伤害并抽 1 张牌。', energyCost: 2, damage: 8, draw: 1, star: 3 },
    { name: '三连斩', desc: '三连快斩，造成 11 点伤害并抽 1 张牌。', energyCost: 3, damage: 11, draw: 1, star: 3 },
    { name: '反击风暴', desc: '风暴式反击，造成 7 点伤害并获得 7 点格挡。', energyCost: 2, damage: 7, block: 7, star: 3 },
    { name: '攻防兼备', desc: '攻防并重，造成 8 点伤害并获得 6 点格挡。', energyCost: 2, damage: 8, block: 6, star: 3 },
    { name: '战神之力', desc: '战神之力涌动，获得 2 点力量。', energyCost: 1, strength: 2, star: 3 },
    { name: '狂暴之心', desc: '狂暴之心燃烧，获得 3 点力量并失去 2 点生命。', energyCost: 2, strength: 3, loseLife: 2, star: 3 },
    { name: '风之敏捷', desc: '御风而行，获得 2 点敏捷并抽 1 张牌。', energyCost: 1, dexterity: 2, draw: 1, star: 3 },
    { name: '虚弱之触', desc: '虚弱之触侵蚀，造成 4 点伤害并使敌人攻击 -25%。', energyCost: 1, damage: 4, applyWeak: 2, star: 3 },
    { name: '易伤打击', desc: '痛击破绽，造成 7 点伤害并施加 3 层易伤。', energyCost: 2, damage: 7, applyVuln: 3, star: 3 },
    { name: '血之祭典', desc: '血之祭典，造成 20 点伤害并失去 6 点生命。', energyCost: 2, damage: 20, loseLife: 6, star: 3 },
    { name: '命运战吼', desc: '命运之吼，抽 3 张牌（消耗）。', energyCost: 0, draw: 3, exhaust: true, star: 3 },
    { name: '坚守', desc: '坚守阵地，获得 12 点格挡，此牌回合结束保留。', energyCost: 2, block: 12, retain: true, star: 3 },
    { name: '四重斩', desc: '四段快斩，造成 4 点伤害 ×4 次。', energyCost: 2, damage: 4, hits: 4, star: 3 },
    { name: '破甲重击', desc: '破甲重击，造成 18 点伤害并无视敌人护盾。', energyCost: 3, damage: 18, pierce: true, star: 3 },
    { name: '腐蚀风暴', desc: '腐蚀风暴席卷，造成 5 点伤害并施加 3 层腐蚀（腐蚀会不断蔓延）。', energyCost: 2, damage: 5, element: 'corrode', elementAmount: 3, star: 3 },
    { name: '铁壁反击', desc: '铁壁防御并伺机反击，获得 8 点格挡，本回合受击反伤 6 点。', energyCost: 2, block: 8, retaliate: 6, star: 3 },
    { name: '短暂狂暴', desc: '燃尽潜能，获得 3 点临时力量并抽 1 张牌。', energyCost: 1, tempStrength: 3, draw: 1, star: 3 },
    { name: '震慑', desc: '一击震慑，造成 3 点伤害并使敌人下回合无法行动。', energyCost: 1, damage: 3, stun: true, star: 3 },
    { name: '磐石', desc: '化身磐石，获得 10 点格挡，本回合格挡不会在受击后清零。', energyCost: 2, block: 10, fortify: true, star: 3 },
    { name: '双重回响', desc: '获得 2 层回响，本回合接下来两张牌的效果将执行两次。', energyCost: 2, echo: 2, star: 3 },
    { name: '战神血誓', desc: '能力：每回合开始时获得 2 点力量并抽 1 张牌。', energyCost: 2, perTurn: { str: 2, draw: 1 }, star: 3 },
    { name: '荆棘之躯', desc: '获得 6 点格挡和 6 点荆棘（整场战斗持续）。', energyCost: 2, block: 6, thorns: 6, star: 3 },
    { name: '破甲缴械', desc: '无视护盾卸下武器，造成 7 点伤害并使敌人攻击永久 -1。', energyCost: 2, damage: 7, pierce: true, enemyAtkDown: 1, star: 3 },
    { name: '连击之刃', desc: '挥出连击，造成 3 点伤害，牌组中每有一张同名卡伤害 +3。', energyCost: 1, damage: 3, synergyDamage: 3, star: 3 },
    { name: '钢铁身躯', desc: '能力：每回合开始时获得 3 点敏捷。', energyCost: 2, perTurn: { dex: 3 }, star: 3 },
  ],
  4: [
    { name: '剑术·奥义', desc: '剑术巅峰奥义，造成 10 点伤害。', energyCost: 1, damage: 10, star: 4 },
    { name: '天地崩击', desc: '天地为之崩裂，造成 21 点伤害。', energyCost: 3, damage: 21, star: 4 },
    { name: '影舞', desc: '影子般舞动，造成 9 点伤害并抽 1 张牌。', energyCost: 1, damage: 9, draw: 1, star: 4 },
    { name: '剧毒之心', desc: '剧毒核心，造成 5 点伤害并施加 8 层剧毒。', energyCost: 1, damage: 5, element: 'poison', elementAmount: 8, star: 4 },
    { name: '火神符', desc: '火神符咒，造成 5 点伤害并施加 8 层灼烧。', energyCost: 1, damage: 5, element: 'fire', elementAmount: 8, star: 4 },
    { name: '雷神符', desc: '雷神符咒，造成 5 点伤害并施加 8 层雷击。', energyCost: 1, damage: 5, element: 'lightning', elementAmount: 8, star: 4 },
    { name: '冰神符', desc: '冰神符咒，造成 5 点伤害并施加 8 层冰封。', energyCost: 1, damage: 5, element: 'ice', elementAmount: 8, star: 4 },
    { name: '绝对防御', desc: '绝对防御架势，获得 15 点格挡。', energyCost: 1, block: 15, star: 4 },
    { name: '无敌壁垒', desc: '无敌的壁垒，获得 24 点格挡。', energyCost: 2, block: 24, star: 4 },
    { name: '圣域', desc: '展开圣域，获得 25 点格挡。', energyCost: 2, block: 25, star: 4 },
    { name: '烈焰炼狱', desc: '炼狱之火，造成 12 点伤害并施加 5 层灼烧。', energyCost: 2, damage: 12, element: 'fire', elementAmount: 5, star: 4 },
    { name: '冰霜炼狱', desc: '炼狱之冰，造成 12 点伤害并施加 5 层冰封。', energyCost: 2, damage: 12, element: 'ice', elementAmount: 5, star: 4 },
    { name: '剧毒炼狱', desc: '炼狱之毒，造成 11 点伤害并施加 6 层剧毒。', energyCost: 2, damage: 11, element: 'poison', elementAmount: 6, star: 4 },
    { name: '雷霆炼狱', desc: '炼狱之雷，造成 12 点伤害并施加 5 层雷击。', energyCost: 2, damage: 12, element: 'lightning', elementAmount: 5, star: 4 },
    { name: '深海炼狱', desc: '炼狱之渊，造成 12 点伤害并施加 5 层水蚀。', energyCost: 2, damage: 12, element: 'water', elementAmount: 5, star: 4 },
    { name: '风神斩', desc: '风神之斩，造成 12 点伤害并施加 5 层风袭。', energyCost: 2, damage: 12, element: 'wind', elementAmount: 5, star: 4 },
    { name: '焚天之火', desc: '焚尽天穹之火，造成 17 点伤害并施加 6 层灼烧。', energyCost: 3, damage: 17, element: 'fire', elementAmount: 6, star: 4 },
    { name: '冰封千里', desc: '冰封千里之地，造成 16 点伤害并施加 6 层冰封。', energyCost: 3, damage: 16, element: 'ice', elementAmount: 6, star: 4 },
    { name: '毒王', desc: '万毒之王，造成 15 点伤害并施加 7 层剧毒。', energyCost: 3, damage: 15, element: 'poison', elementAmount: 7, star: 4 },
    { name: '雷神之锤', desc: '雷神掷出之锤，造成 17 点伤害并施加 6 层雷击。', energyCost: 3, damage: 17, element: 'lightning', elementAmount: 6, star: 4 },
    { name: '汪洋', desc: '汪洋倾覆，造成 17 点伤害并施加 6 层水蚀。', energyCost: 3, damage: 17, element: 'water', elementAmount: 6, star: 4 },
    { name: '台风', desc: '台风过境，造成 17 点伤害并施加 6 层风袭。', energyCost: 3, damage: 17, element: 'wind', elementAmount: 6, star: 4 },
    { name: '血魔爪', desc: '血魔之爪，造成 13 点伤害并恢复 5 点生命。', energyCost: 2, damage: 13, heal: 5, star: 4 },
    { name: '灵魂收割', desc: '收割灵魂，造成 12 点伤害并恢复 6 点生命。', energyCost: 2, damage: 12, heal: 6, star: 4 },
    { name: '生命之泉', desc: '涌出生命之泉，恢复 9 点生命。', energyCost: 1, heal: 9, star: 4 },
    { name: '圣水', desc: '圣水治愈，恢复 12 点生命。', energyCost: 2, heal: 12, star: 4 },
    { name: '超凡冥想', desc: '超凡入圣，获得 5 点能量。', energyCost: 0, energyGain: 5, star: 4 },
    { name: '战争机器', desc: '战争机器轰鸣，获得 4 点能量并抽 1 张牌。', energyCost: 1, energyGain: 4, draw: 1, star: 4 },
    { name: '运筹帷幄', desc: '运筹帷幄之中，抽 4 张牌并获得 1 点能量。', energyCost: 1, draw: 4, energyGain: 1, star: 4 },
    { name: '全局洞察', desc: '洞悉全局，抽 5 张牌。', energyCost: 2, draw: 5, star: 4 },
    { name: '四连斩', desc: '四段连斩，造成 13 点伤害并抽 2 张牌。', energyCost: 3, damage: 13, draw: 2, star: 4 },
    { name: '狂暴连击', desc: '狂暴乱击，造成 15 点伤害并抽 1 张牌。', energyCost: 3, damage: 15, draw: 1, star: 4 },
    { name: '完美反击', desc: '完美防守反击，造成 10 点伤害并获得 9 点格挡。', energyCost: 2, damage: 10, block: 9, star: 4 },
    { name: '攻守兼备·极', desc: '极致攻防，造成 11 点伤害并获得 8 点格挡。', energyCost: 2, damage: 11, block: 8, star: 4 },
    { name: '战神附体', desc: '战神附体，获得 3 点力量。', energyCost: 1, strength: 3, star: 4 },
    { name: '圣体', desc: '圣体显化，获得 3 点力量与 1 点敏捷。', energyCost: 2, strength: 3, dexterity: 1, star: 4 },
    { name: '疾风', desc: '疾风缠身，获得 3 点敏捷。', energyCost: 1, dexterity: 3, star: 4 },
    { name: '虚弱诅咒', desc: '诅咒削弱，造成 6 点伤害并使敌人攻击 -25%。', energyCost: 1, damage: 6, applyWeak: 2, star: 4 },
    { name: '易伤爆发', desc: '爆发破绽，造成 10 点伤害并施加 4 层易伤。', energyCost: 2, damage: 10, applyVuln: 4, star: 4 },
    { name: '血之献祭', desc: '血之献祭，造成 26 点伤害并失去 7 点生命。', energyCost: 2, damage: 26, loseLife: 7, star: 4 },
    { name: '战争号角', desc: '吹响战争号角，抽 4 张牌（消耗）。', energyCost: 0, draw: 4, exhaust: true, star: 4 },
    { name: '泰山', desc: '稳如泰山，获得 18 点格挡，此牌回合结束保留。', energyCost: 2, block: 18, retain: true, star: 4 },
    { name: '五重连击', desc: '五段连击，造成 6 点伤害 ×5 次。', energyCost: 3, damage: 6, hits: 5, star: 4 },
    { name: '破甲斩·极', desc: '极致破甲斩，造成 16 点伤害并无视敌人护盾。', energyCost: 2, damage: 16, pierce: true, star: 4 },
    { name: '腐蚀之海', desc: '腐蚀之海倾泻，造成 7 点伤害并施加 4 层腐蚀（腐蚀会不断蔓延）。', energyCost: 2, damage: 7, element: 'corrode', elementAmount: 4, star: 4 },
    { name: '以血还血', desc: '鲜血作刃，造成 9 点伤害并恢复等量生命。', energyCost: 2, damage: 9, lifesteal: true, star: 4 },
    { name: '连环反击', desc: '摆出连环反击架势，获得 12 点格挡，本回合受击反伤 8 点。', energyCost: 2, block: 12, retaliate: 8, star: 4 },
    { name: '眩晕重击', desc: '沉重一击震晕敌人，造成 9 点伤害并使敌人下回合无法行动。', energyCost: 3, damage: 9, stun: true, star: 4 },
    { name: '剧毒炼金', desc: '炼金术引爆毒素，造成 3 点伤害并立即结算毒层 ×3（清除剧毒）。', energyCost: 2, damage: 3, poisonBurst: true, burstMult: 3, star: 4 },
    { name: '回响风暴', desc: '造成 6 点伤害并施加 3 层腐蚀（会蔓延），本回合下一张牌的效果将执行两次。', energyCost: 2, damage: 6, element: 'corrode', elementAmount: 3, echo: 1, star: 4 },
    { name: '恶魔之力', desc: '能力：每回合开始时获得 3 点力量。', energyCost: 2, perTurn: { str: 3 }, star: 4 },
    { name: '金刚荆棘', desc: '获得 10 点格挡和 8 点荆棘（整场战斗持续）。', energyCost: 2, block: 10, thorns: 8, star: 4 },
    { name: '战争缴械', desc: '彻底缴械，造成 10 点伤害并使敌人攻击永久 -2。', energyCost: 2, damage: 10, enemyAtkDown: 2, star: 4 },
    { name: '同调斩', desc: '与同名之刃共鸣，造成 6 点伤害，牌组中每有一张同名卡伤害 +4。', energyCost: 1, damage: 6, synergyDamage: 4, star: 4 },
    { name: '清算风暴', desc: '弃置所有手牌，每弃一张获得 3 点格挡并造成 2 点伤害。', energyCost: 1, discardGainBlock: 3, discardGainDamage: 2, star: 4 },
  ],
  5: [
    { name: '剑术·天启', desc: '天启之剑，造成 12 点伤害。', energyCost: 1, damage: 12, star: 5 },
    { name: '混沌重击', desc: '混沌之力倾泻，造成 26 点伤害。', energyCost: 3, damage: 26, star: 5 },
    { name: '影刃', desc: '影中之刃，造成 11 点伤害并抽 2 张牌。', energyCost: 1, damage: 11, draw: 2, star: 5 },
    { name: '剧毒真主', desc: '剧毒真主降临，造成 6 点伤害并施加 10 层剧毒。', energyCost: 1, damage: 6, element: 'poison', elementAmount: 10, star: 5 },
    { name: '火神降临', desc: '火神降临，造成 6 点伤害并施加 10 层灼烧。', energyCost: 1, damage: 6, element: 'fire', elementAmount: 10, star: 5 },
    { name: '雷神真言', desc: '雷神真言，造成 6 点伤害并施加 10 层雷击。', energyCost: 1, damage: 6, element: 'lightning', elementAmount: 10, star: 5 },
    { name: '冰神真言', desc: '冰神真言，造成 6 点伤害并施加 10 层冰封。', energyCost: 1, damage: 6, element: 'ice', elementAmount: 10, star: 5 },
    { name: '神之领域', desc: '展开神之领域，获得 19 点格挡。', energyCost: 1, block: 19, star: 5 },
    { name: '绝对壁垒', desc: '绝对不破的壁垒，获得 30 点格挡。', energyCost: 2, block: 30, star: 5 },
    { name: '烈焰苍穹', desc: '苍穹焚尽，造成 15 点伤害并施加 6 层灼烧。', energyCost: 2, damage: 15, element: 'fire', elementAmount: 6, star: 5 },
    { name: '寒冰苍穹', desc: '苍穹冰封，造成 15 点伤害并施加 6 层冰封。', energyCost: 2, damage: 15, element: 'ice', elementAmount: 6, star: 5 },
    { name: '剧毒苍穹', desc: '苍穹染毒，造成 14 点伤害并施加 7 层剧毒。', energyCost: 2, damage: 14, element: 'poison', elementAmount: 7, star: 5 },
    { name: '雷霆苍穹', desc: '苍穹落雷，造成 15 点伤害并施加 6 层雷击。', energyCost: 2, damage: 15, element: 'lightning', elementAmount: 6, star: 5 },
    { name: '汪洋苍穹', desc: '苍穹倾海，造成 15 点伤害并施加 6 层水蚀。', energyCost: 2, damage: 15, element: 'water', elementAmount: 6, star: 5 },
    { name: '风神苍穹', desc: '苍穹风暴，造成 15 点伤害并施加 6 层风袭。', energyCost: 2, damage: 15, element: 'wind', elementAmount: 6, star: 5 },
    { name: '恒星爆发', desc: '恒星爆炸之力，造成 21 点伤害并施加 7 层灼烧。', energyCost: 3, damage: 21, element: 'fire', elementAmount: 7, star: 5 },
    { name: '绝对零度·终', desc: '终焉之冰，造成 20 点伤害并施加 7 层冰封。', energyCost: 3, damage: 20, element: 'ice', elementAmount: 7, star: 5 },
    { name: '万毒之王', desc: '毒之君王，造成 19 点伤害并施加 8 层剧毒。', energyCost: 3, damage: 19, element: 'poison', elementAmount: 8, star: 5 },
    { name: '雷神降临', desc: '雷神亲临，造成 21 点伤害并施加 7 层雷击。', energyCost: 3, damage: 21, element: 'lightning', elementAmount: 7, star: 5 },
    { name: '海神之怒', desc: '海神之怒，造成 21 点伤害并施加 7 层水蚀。', energyCost: 3, damage: 21, element: 'water', elementAmount: 7, star: 5 },
    { name: '风神降临', desc: '风神亲临，造成 21 点伤害并施加 7 层风袭。', energyCost: 3, damage: 21, element: 'wind', elementAmount: 7, star: 5 },
    { name: '血皇之牙', desc: '血皇之牙，造成 16 点伤害并恢复 6 点生命。', energyCost: 2, damage: 16, heal: 6, star: 5 },
    { name: '灵魂吞噬', desc: '吞噬灵魂，造成 15 点伤害并恢复 7 点生命。', energyCost: 2, damage: 15, heal: 7, star: 5 },
    { name: '生命之源', desc: '生命本源涌动，恢复 12 点生命。', energyCost: 1, heal: 12, star: 5 },
    { name: '神药', desc: '饮下神药，恢复 16 点生命。', energyCost: 2, heal: 16, star: 5 },
    { name: '神级冥想', desc: '与神共鸣，获得 6 点能量。', energyCost: 0, energyGain: 6, star: 5 },
    { name: '终极战争机器', desc: '终极引擎轰鸣，获得 5 点能量并抽 1 张牌。', energyCost: 1, energyGain: 5, draw: 1, star: 5 },
    { name: '洞悉一切', desc: '洞悉万物，抽 5 张牌并获得 2 点能量。', energyCost: 1, draw: 5, energyGain: 2, star: 5 },
    { name: '至高洞察', desc: '至高之洞察，抽 6 张牌。', energyCost: 2, draw: 6, star: 5 },
    { name: '战意封神', desc: '战意封神，下回合攻击伤害 ×2 并抽 2 张牌。', energyCost: 0, doubleNext: true, draw: 2, star: 5 },
    { name: '五连斩', desc: '五段神斩，造成 16 点伤害并抽 3 张牌。', energyCost: 3, damage: 16, draw: 3, star: 5 },
    { name: '狂暴乱舞', desc: '狂暴之乱舞，造成 18 点伤害并抽 2 张牌。', energyCost: 3, damage: 18, draw: 2, star: 5 },
    { name: '神的反击', desc: '神之反击，造成 13 点伤害并获得 11 点格挡。', energyCost: 2, damage: 13, block: 11, star: 5 },
    { name: '攻守兼备·神', desc: '神级攻防，造成 14 点伤害并获得 10 点格挡。', energyCost: 2, damage: 14, block: 10, star: 5 },
    { name: '不朽守护', desc: '不朽之守护，获得 16 点格挡并免疫本回合伤害。', energyCost: 3, block: 16, invulnerable: true, star: 5 },
    { name: '战神降临', desc: '战神降临，获得 4 点力量与 10 点格挡。', energyCost: 2, strength: 4, block: 10, star: 5 },
    { name: '天神下凡', desc: '天神下凡，获得 4 点敏捷并抽 2 张牌。', energyCost: 2, dexterity: 4, draw: 2, star: 5 },
    { name: '虚弱大咒', desc: '虚弱大咒，造成 8 点伤害并使敌人攻击 -25%。', energyCost: 1, damage: 8, applyWeak: 3, star: 5 },
    { name: '易伤天罚', desc: '天罚易伤，造成 14 点伤害并施加 5 层易伤。', energyCost: 3, damage: 14, applyVuln: 5, star: 5 },
    { name: '血之祭天', desc: '血之祭天，造成 32 点伤害并失去 8 点生命。', energyCost: 3, damage: 32, loseLife: 8, star: 5 },
    { name: '永恒战吼', desc: '永恒战吼，抽 5 张牌（消耗）。', energyCost: 0, draw: 5, exhaust: true, star: 5 },
    { name: '不动明王', desc: '不动明王身，获得 24 点格挡，此牌回合结束保留。', energyCost: 3, block: 24, retain: true, star: 5 },
    { name: '六道连斩', desc: '六道连斩，造成 8 点伤害 ×6 次。', energyCost: 3, damage: 8, hits: 6, star: 5 },
    { name: '破甲神斩', desc: '破甲神斩，造成 22 点伤害并无视敌人护盾。', energyCost: 2, damage: 22, pierce: true, star: 5 },
    { name: '永恒腐蚀', desc: '永恒腐蚀之力，造成 9 点伤害并施加 5 层腐蚀（腐蚀会不断蔓延）。', energyCost: 2, damage: 9, element: 'corrode', elementAmount: 5, star: 5 },
    { name: '鲜血契约', desc: '以血养剑，造成 13 点伤害并恢复等量生命。', energyCost: 2, damage: 13, lifesteal: true, star: 5 },
    { name: '不动如山', desc: '岿然不动，获得 15 点格挡，本回合受击反伤 12 点。', energyCost: 2, block: 15, retaliate: 12, star: 5 },
    { name: '神之震慑', desc: '神威震慑，造成 12 点伤害并使敌人下回合无法行动，抽 1 张牌。', energyCost: 3, damage: 12, stun: true, draw: 1, star: 5 },
    { name: '神之壁垒', desc: '神之壁垒，获得 18 点格挡，本回合格挡不会在受击后清零。', energyCost: 2, block: 18, fortify: true, star: 5 },
    { name: '时空回响', desc: '获得 3 层回响并抽 1 张牌，接下来三张牌的效果将执行两次。', energyCost: 2, echo: 3, draw: 1, star: 5 },
    { name: '魔神降临', desc: '能力：每回合开始时获得 3 点力量、2 点敏捷和 4 点格挡。', energyCost: 3, perTurn: { str: 3, dex: 2, block: 4 }, star: 5 },
    { name: '万棘之王', desc: '获得 12 点格挡和 10 点荆棘（整场战斗持续）。', energyCost: 2, block: 12, thorns: 10, star: 5 },
    { name: '绝命缴械', desc: '无视护盾彻底缴械，造成 13 点伤害并使敌人攻击永久 -2。', energyCost: 2, damage: 13, pierce: true, enemyAtkDown: 2, star: 5 },
    { name: '咆哮', desc: '越战越勇，造成 8 点伤害，本场战斗每次使用后伤害 +5。', energyCost: 1, damage: 8, rampage: 5, star: 5 },
    { name: '湮灭', desc: '弃置所有手牌，每弃一张获得 6 点格挡。', energyCost: 2, discardGainBlock: 6, star: 5 },
  ],
}

// ---- 流派羁绊：牌组中同流派卡达到阈值触发被动（参考自走棋羁绊 / 杀戮尖塔构筑） ----
// 档位：2 张 = 1 阶，4 张 = 2 阶
