/* 数据模块：characters —— 角色定义（经 G.def.characters 工厂注册）
 * 扩展方式：任意文件调用 G.def.characters({ id: {...} }) 即可叠加/新增角色
 */
var G = window.GAME.data || (window.GAME.data = {})
G.def.characters({
  hunter: {
    name: '猎人', desc: '长期猎杀异星生物，熟悉搏斗与血腥。', loadingCoef: 1,
    hungerMax: 150, thirstMax: 130,
    bonus: { lifeBonus: 20, energyBonus: 2 },
    carryBonus: 10,
    trait: { combatDamage: 1 },
    traitDesc: '战斗造成的伤害 +1',
    attrs: { str: 4, agi: 3, con: 2, int: 1 },
    startItems: { hide: 2, metal: 1, fungus: 2 },
    itemsDesc: '开局：兽皮×2、金属残片×1、菌丝块×2',
    ability: { id: 'hunter_focus', name: '狩猎本能', desc: '下一次猎杀战斗中，你的卡牌伤害 +2。', time: 20, kind: 'combat', value: 2 },
    // 专属卡组：猎杀爆发流，高伤害
    battleCards: [
      { name: '猎手突刺', desc: '瞄准要害突刺，造成 5 点伤害。', energyCost: 1, damage: 5, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '猎手突刺', desc: '瞄准要害突刺，造成 5 点伤害。', energyCost: 1, damage: 5, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '猛禽撕咬', desc: '扑咬猎物，造成 8 点伤害。', energyCost: 2, damage: 8, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '猛禽撕咬', desc: '扑咬猎物，造成 8 点伤害。', energyCost: 2, damage: 8, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '断喉一击', desc: '致命一咬，造成 13 点伤害。', energyCost: 3, damage: 13, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '追踪猎杀', desc: '锁定猎物，造成 6 点伤害并抽 1 张牌。', energyCost: 2, damage: 6, block: 0, heal: 0, energyGain: 0, draw: 1 },
      { name: '膝撞', desc: '近距离膝击，造成 5 点伤害。', energyCost: 1, damage: 5, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '刺拳', desc: '快如闪电的试探攻击，造成 2 点伤害。', energyCost: 0, damage: 2, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '翻滚闪避', desc: '侧身翻滚，获得 8 点格挡。', energyCost: 1, damage: 0, block: 8, heal: 0, energyGain: 0, draw: 0 },
      { name: '翻滚闪避', desc: '侧身翻滚，获得 8 点格挡。', energyCost: 1, damage: 0, block: 8, heal: 0, energyGain: 0, draw: 0 },
      { name: '兽血沸腾', desc: '猎杀的本能翻涌，凝聚战斗能量 +2。', energyCost: 0, damage: 0, block: 0, heal: 0, energyGain: 2, draw: 0 },
    ],
  },
  scholar: {
    name: '学者', desc: '痴迷于异星的一切知识。',
    hungerMax: 120, thirstMax: 120,
    bonus: { data: 3 },
    trait: { researchGain: 1 },
    traitDesc: '研究获得的星之记忆 +1',
    attrs: { str: 1, agi: 1, con: 2, int: 6 },
    startItems: { specimen: 2 },
    itemsDesc: '开局：生物样本×2',
    ability: { id: 'scholar_boost', name: '灵感迸发', desc: '接下来的 2 次研究获得的星之记忆翻倍。', time: 20, kind: 'researchBoost', value: 2 },
    // 专属卡组：知识驱动流，多抽牌多能量
    battleCards: [
      { name: '标本解析', desc: '剖析标本，造成 3 点伤害并抽 1 张牌。', energyCost: 1, damage: 3, block: 0, heal: 0, energyGain: 0, draw: 1 },
      { name: '标本解析', desc: '剖析标本，造成 3 点伤害并抽 1 张牌。', energyCost: 1, damage: 3, block: 0, heal: 0, energyGain: 0, draw: 1 },
      { name: '洞察', desc: '看穿敌人，造成 4 点伤害并抽 1 张牌。', energyCost: 1, damage: 4, block: 0, heal: 0, energyGain: 0, draw: 1 },
      { name: '星之记忆冲击', desc: '凝聚星之记忆冲击，造成 6 点伤害。', energyCost: 2, damage: 6, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '星之记忆冲击', desc: '凝聚星之记忆冲击，造成 6 点伤害。', energyCost: 2, damage: 6, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '精密解剖', desc: '精准解剖，造成 7 点伤害。', energyCost: 2, damage: 7, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '理论护盾', desc: '构建立论屏障，获得 6 点格挡。', energyCost: 1, damage: 0, block: 6, heal: 0, energyGain: 0, draw: 0 },
      { name: '理论护盾', desc: '构建立论屏障，获得 6 点格挡。', energyCost: 1, damage: 0, block: 6, heal: 0, energyGain: 0, draw: 0 },
      { name: '知识汲取', desc: '汲取知识，凝聚战斗能量 +2。', energyCost: 0, damage: 0, block: 0, heal: 0, energyGain: 2, draw: 0 },
      { name: '知识汲取', desc: '汲取知识，凝聚战斗能量 +2。', energyCost: 0, damage: 0, block: 0, heal: 0, energyGain: 2, draw: 0 },
    ],
  },
  medic: {
    name: '医生', desc: '精通解剖与急救，懂得处理伤口。', loadingCoef: 1,
    hungerMax: 130, thirstMax: 145,
    bonus: { data: 2, lifeBonus: 10, energyBonus: 1 },
    carryBonus: 3,
    trait: { bleedReduction: 15 },
    traitDesc: '受伤流血几率 -15%',
    attrs: { str: 2, agi: 2, con: 3, int: 3 },
    startItems: { fiber: 3 },
    itemsDesc: '开局：异星纤维×3',
    ability: { id: 'medic_firstaid', name: '急救处理', desc: '立即止血并恢复 20 点生命。', time: 20, kind: 'heal', value: 20 },
    // 专属卡组：医疗防御流，能打能回
    battleCards: [
      { name: '手术刀', desc: '精准割裂，造成 4 点伤害。', energyCost: 1, damage: 4, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '手术刀', desc: '精准割裂，造成 4 点伤害。', energyCost: 1, damage: 4, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '解剖刀', desc: '切入要害，造成 6 点伤害。', energyCost: 2, damage: 6, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '麻醉针', desc: '扎入麻醉针，造成 3 点伤害并获得 3 点格挡。', energyCost: 1, damage: 3, block: 3, heal: 0, energyGain: 0, draw: 0 },
      { name: '麻醉针', desc: '扎入麻醉针，造成 3 点伤害并获得 3 点格挡。', energyCost: 1, damage: 3, block: 3, heal: 0, energyGain: 0, draw: 0 },
      { name: '绷带包扎', desc: '迅速包扎，恢复 6 点生命。', energyCost: 1, damage: 0, block: 0, heal: 6, energyGain: 0, draw: 0 },
      { name: '绷带包扎', desc: '迅速包扎，恢复 6 点生命。', energyCost: 1, damage: 0, block: 0, heal: 6, energyGain: 0, draw: 0 },
      { name: '急救处理', desc: '临场急救，恢复 3 点生命。', energyCost: 0, damage: 0, block: 0, heal: 3, energyGain: 0, draw: 0 },
      { name: '防护服', desc: '展开防护服，获得 10 点格挡。', energyCost: 2, damage: 0, block: 10, heal: 0, energyGain: 0, draw: 0 },
      { name: '医疗箱', desc: '打开医疗箱，恢复 8 点生命并获得 4 点格挡。', energyCost: 2, damage: 0, block: 4, heal: 8, energyGain: 0, draw: 0 },
    ],
  },
  drifter: {
    name: '漂泊者', desc: '体内循环异于常人，格外耐饥渴。', loadingCoef: 1,
    hungerMax: 170, thirstMax: 170,
    bonus: { lifeBonus: 30, energyBonus: 4 },
    carryBonus: 16,
    trait: { metabolism: 5 },
    traitDesc: '每日饥饿/饥渴消耗 -5',
    attrs: { str: 3, agi: 3, con: 4, int: 1 },
    startItems: { fungus: 2, brine: 1 },
    itemsDesc: '开局：菌丝块×2、盐水×1',
    ability: { id: 'drifter_breath', name: '潮汐呼吸', desc: '立即恢复 6 点耐力与 6 点精神。', time: 10, kind: 'restore', value: 6 },
    // 专属卡组：荒野生存流，攻守均衡
    battleCards: [
      { name: '求生挥击', desc: '徒手求生，造成 5 点伤害。', energyCost: 1, damage: 5, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '求生挥击', desc: '徒手求生，造成 5 点伤害。', energyCost: 1, damage: 5, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '岩石投掷', desc: '捡起石块砸出，造成 2 点伤害。', energyCost: 0, damage: 2, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '荒地冲刺', desc: '咬牙冲刺，造成 6 点伤害并抽 1 张牌。', energyCost: 2, damage: 6, block: 0, heal: 0, energyGain: 0, draw: 1 },
      { name: '荒地冲刺', desc: '咬牙冲刺，造成 6 点伤害并抽 1 张牌。', energyCost: 2, damage: 6, block: 0, heal: 0, energyGain: 0, draw: 1 },
      { name: '缠斗', desc: '贴身缠斗，造成 4 点伤害并获得 5 点格挡。', energyCost: 2, damage: 4, block: 5, heal: 0, energyGain: 0, draw: 0 },
      { name: '缠斗', desc: '贴身缠斗，造成 4 点伤害并获得 5 点格挡。', energyCost: 2, damage: 4, block: 5, heal: 0, energyGain: 0, draw: 0 },
      { name: '硬撑', desc: '咬牙硬撑，获得 7 点格挡。', energyCost: 1, damage: 0, block: 7, heal: 0, energyGain: 0, draw: 0 },
      { name: '硬撑', desc: '咬牙硬撑，获得 7 点格挡。', energyCost: 1, damage: 0, block: 7, heal: 0, energyGain: 0, draw: 0 },
      { name: '忍耐', desc: '忍耐伤痛，恢复 4 点生命。', energyCost: 1, damage: 0, block: 0, heal: 4, energyGain: 0, draw: 0 },
      { name: '深呼吸', desc: '调整呼吸，凝聚战斗能量 +2。', energyCost: 0, damage: 0, block: 0, heal: 0, energyGain: 2, draw: 0 },
    ],
  },
  debugger: {
    name: '调试者', desc: '仅供调试使用：超强血量与属性的测试角色。', loadingCoef: 0.1,
    hungerMax: 200, thirstMax: 200,
    bonus: { lifeBonus: 999900, energyBonus: 10 },
    trait: { combatDamage: 50, researchGain: 10, bleedReduction: 100, metabolism: 100 },
    traitDesc: '调试用：战斗伤害+50、研究+10、免疫流血、代谢极快',
    attrs: { str: 20, agi: 20, con: 20, int: 20 },
    carryLimit: 99999999,
    startItems: { fungus: 20, brine: 20, fiber: 20, metal: 20, wood: 20, stone: 20, bone: 20, clay: 20, resin: 20, specimen: 20, hide: 10 },
    itemsDesc: '调试用：大量初始物资',
    ability: { id: 'debug_heal', name: '调试恢复', desc: '恢复 9999 点生命与全部耐力精神。', time: 1, kind: 'heal', value: 9999 },
    // 专属卡组：调试用超高伤害
    battleCards: [
      { name: '调试重击', desc: '调试用：造成 9999 点伤害。', energyCost: 0, damage: 9999, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '调试重击', desc: '调试用：造成 9999 点伤害。', energyCost: 0, damage: 9999, block: 0, heal: 0, energyGain: 0, draw: 0 },
      { name: '调试格挡', desc: '调试用：获得 999 点格挡。', energyCost: 0, damage: 0, block: 999, heal: 0, energyGain: 0, draw: 0 },
      { name: '调试治疗', desc: '调试用：恢复 9999 点生命。', energyCost: 0, damage: 0, block: 0, heal: 9999, energyGain: 0, draw: 0 },
      { name: '调试充能', desc: '调试用：能量 +5。', energyCost: 0, damage: 0, block: 0, heal: 0, energyGain: 5, draw: 0 },
    ],
  },
})

// ---- 研究升级 / 临时制造 ----
